package ir.danialchoopan.medimate.presentation.theme

import androidx.compose.ui.graphics.Color

// ── Light Theme ──────────────────────────────────────────────
val md_theme_light_primary = Color(0xFF1B6D3D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA4F5B4)
val md_theme_light_onPrimaryContainer = Color(0xFF00210E)
val md_theme_light_secondary = Color(0xFF506352)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD3E8D2)
val md_theme_light_onSecondaryContainer = Color(0xFF0E1F12)
val md_theme_light_tertiary = Color(0xFF3A656E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBDEAF5)
val md_theme_light_onTertiaryContainer = Color(0xFF001F26)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF7FBF2)
val md_theme_light_onBackground = Color(0xFF191D19)
val md_theme_light_surface = Color(0xFFF7FBF2)
val md_theme_light_onSurface = Color(0xFF191D19)
val md_theme_light_surfaceVariant = Color(0xFFDDE5DA)
val md_theme_light_onSurfaceVariant = Color(0xFF414941)
val md_theme_light_outline = Color(0xFF717971)
val md_theme_light_outlineVariant = Color(0xFFC0C9BE)
val md_theme_light_inverseSurface = Color(0xFF2E322D)
val md_theme_light_inverseOnSurface = Color(0xFFEFF5EC)
val md_theme_light_inversePrimary = Color(0xFF89D899)
val md_theme_light_surfaceTint = Color(0xFF1B6D3D)
val md_theme_light_surfaceDim = Color(0xFFD7DCD4)
val md_theme_light_surfaceBright = Color(0xFFF7FBF2)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF1F5ED)
val md_theme_light_surfaceContainer = Color(0xFFEBF0E7)
val md_theme_light_surfaceContainerHigh = Color(0xFFE6EAE2)
val md_theme_light_surfaceContainerHighest = Color(0xFFE0E4DC)

// ── Dark Theme ───────────────────────────────────────────────
val md_theme_dark_primary = Color(0xFF89D899)
val md_theme_dark_onPrimary = Color(0xFF00391E)
val md_theme_dark_primaryContainer = Color(0xFF00522C)
val md_theme_dark_onPrimaryContainer = Color(0xFFA4F5B4)
val md_theme_dark_secondary = Color(0xFFB7CCB7)
val md_theme_dark_onSecondary = Color(0xFF233426)
val md_theme_dark_secondaryContainer = Color(0xFF394B3C)
val md_theme_dark_onSecondaryContainer = Color(0xFFD3E8D2)
val md_theme_dark_tertiary = Color(0xFFA2CED8)
val md_theme_dark_onTertiary = Color(0xFF01363F)
val md_theme_dark_tertiaryContainer = Color(0xFF204D56)
val md_theme_dark_onTertiaryContainer = Color(0xFFBDEAF5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191D19)
val md_theme_dark_onBackground = Color(0xFFE1E3DB)
val md_theme_dark_surface = Color(0xFF191D19)
val md_theme_dark_onSurface = Color(0xFFE1E3DB)
val md_theme_dark_surfaceVariant = Color(0xFF414941)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C9BE)
val md_theme_dark_outline = Color(0xFF8A938A)
val md_theme_dark_outlineVariant = Color(0xFF414941)
val md_theme_dark_inverseSurface = Color(0xFFE1E3DB)
val md_theme_dark_inverseOnSurface = Color(0xFF191D19)
val md_theme_dark_inversePrimary = Color(0xFF1B6D3D)
val md_theme_dark_surfaceTint = Color(0xFF89D899)
val md_theme_dark_surfaceDim = Color(0xFF191D19)
val md_theme_dark_surfaceBright = Color(0xFF3F433E)
val md_theme_dark_surfaceContainerLowest = Color(0xFF141814)
val md_theme_dark_surfaceContainerLow = Color(0xFF212521)
val md_theme_dark_surfaceContainer = Color(0xFF262A25)
val md_theme_dark_surfaceContainerHigh = Color(0xFF313530)
val md_theme_dark_surfaceContainerHighest = Color(0xFF3C403B)

// ── Semantic Colors ──────────────────────────────────────────
val SeveritySevere = Color(0xFFD32F2F)
val SeverityModerate = Color(0xFFF57C00)
val SeverityMild = Color(0xFF388E3C)
val StatusTaken = Color(0xFF1B6D3D)
val StatusMissed = Color(0xFFD32F2F)
val StatusSnoozed = Color(0xFFF57C00)
