package ir.danialchoopan.medimate.presentation.theme

import androidx.compose.ui.graphics.Color

// ── Light Theme - Vibrant Teal ──────────────────────────────
val md_theme_light_primary = Color(0xFF00897B)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF80CBC4)
val md_theme_light_onPrimaryContainer = Color(0xFF002020)
val md_theme_light_secondary = Color(0xFF4DB6AC)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFB2DFDB)
val md_theme_light_onSecondaryContainer = Color(0xFF003D36)
val md_theme_light_tertiary = Color(0xFFFF7043)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFCCBC)
val md_theme_light_onTertiaryContainer = Color(0xFF3E0400)
val md_theme_light_error = Color(0xFFE53935)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFCDD2)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFE0F2F1)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFE0F2F1)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFB2DFDB)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4946)
val md_theme_light_outline = Color(0xFF6F7976)
val md_theme_light_outlineVariant = Color(0xFFB2DFDB)
val md_theme_light_inverseSurface = Color(0xFF2E3132)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F2)
val md_theme_light_inversePrimary = Color(0xFF80CBC4)
val md_theme_light_surfaceTint = Color(0xFF00897B)
val md_theme_light_surfaceDim = Color(0xFFB0C8C5)
val md_theme_light_surfaceBright = Color(0xFFE0F2F1)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFD6ECEA)
val md_theme_light_surfaceContainer = Color(0xFFCEE6E4)
val md_theme_light_surfaceContainerHigh = Color(0xFFC4E0DE)
val md_theme_light_surfaceContainerHighest = Color(0xFFB0C8C5)

// ── Dark Theme - Deep Teal ──────────────────────────────────
val md_theme_dark_primary = Color(0xFF80CBC4)
val md_theme_dark_onPrimary = Color(0xFF003731)
val md_theme_dark_primaryContainer = Color(0xFF005048)
val md_theme_dark_onPrimaryContainer = Color(0xFF80CBC4)
val md_theme_dark_secondary = Color(0xFF80CBC4)
val md_theme_dark_onSecondary = Color(0xFF003731)
val md_theme_dark_secondaryContainer = Color(0xFF005048)
val md_theme_dark_onSecondaryContainer = Color(0xFFB2DFDB)
val md_theme_dark_tertiary = Color(0xFFFF8A65)
val md_theme_dark_onTertiary = Color(0xFF5C1900)
val md_theme_dark_tertiaryContainer = Color(0xFF7F3000)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFCCBC)
val md_theme_dark_error = Color(0xFFEF9A9A)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFFFCDD2)
val md_theme_dark_background = Color(0xFF0D1F1C)
val md_theme_dark_onBackground = Color(0xFFE0E3E1)
val md_theme_dark_surface = Color(0xFF0D1F1C)
val md_theme_dark_onSurface = Color(0xFFE0E3E1)
val md_theme_dark_surfaceVariant = Color(0xFF4A5855)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C9C6)
val md_theme_dark_outline = Color(0xFF8A9491)
val md_theme_dark_outlineVariant = Color(0xFF4A5855)
val md_theme_dark_inverseSurface = Color(0xFFE0E3E1)
val md_theme_dark_inverseOnSurface = Color(0xFF0D1F1C)
val md_theme_dark_inversePrimary = Color(0xFF006B60)
val md_theme_dark_surfaceTint = Color(0xFF80CBC4)
val md_theme_dark_surfaceDim = Color(0xFF0D1F1C)
val md_theme_dark_surfaceBright = Color(0xFF334442)
val md_theme_dark_surfaceContainerLowest = Color(0xFF081A17)
val md_theme_dark_surfaceContainerLow = Color(0xFF152724)
val md_theme_dark_surfaceContainer = Color(0xFF192B29)
val md_theme_dark_surfaceContainerHigh = Color(0xFF243634)
val md_theme_dark_surfaceContainerHighest = Color(0xFF2F413F)

// ── Semantic Colors ──────────────────────────────────────────
val SeveritySevere = Color(0xFFE53935)
val SeverityModerate = Color(0xFFFF9800)
val SeverityMild = Color(0xFF4CAF50)
val StatusTaken = Color(0xFF00897B)
val StatusMissed = Color(0xFFE53935)
val StatusSnoozed = Color(0xFFFF9800)

// ── Gradient Colors ──────────────────────────────────────────
val GradientStart = Color(0xFF00897B)
val GradientMid = Color(0xFF26A69A)
val GradientEnd = Color(0xFF80CBC4)
val GradientOrangeStart = Color(0xFFFF7043)
val GradientOrangeEnd = Color(0xFFFFAB91)
